// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "openhorizon-sapient-react-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "SapientReactNativeSpec.h"

@interface SapientReactNative : NSObject <NativeSapientReactNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface SapientReactNative : NSObject <RCTBridgeModule>
#endif

@end