#ifndef OPENHORIZON_SAPIENTREACTNATIVE_H
#define OPENHORIZON_SAPIENTREACTNATIVE_H
// Generated by uniffi-bindgen-react-native
#include <cstdint>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvoker.h>

namespace openhorizon_sapientreactnative {
  using namespace facebook;

  uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker);
  uint8_t cleanupRustCrate(jsi::Runtime &runtime);
}

#endif /* OPENHORIZON_SAPIENTREACTNATIVE_H */