// Generated by uniffi-bindgen-react-native
#include "openhorizon-sapient-react-native.h"
#include "generated/sapient_ffi.hpp"

namespace openhorizon_sapientreactnative {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeSapientFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}