// swift-tools-version:5.9
// Sample chat app over the packaged SAPIENT Swift bindings.
//
// Requires the generated package to exist first:
//   ./scripts/package-swift.sh          (from the repo root)
// then:
//   swift run SapientChatMac            (macOS app, from this directory)
//   xcodegen && open SapientChat.xcodeproj   (iOS app — see README.md)
import PackageDescription

// NOTE: the package name must differ from the Xcode project/target name
// ("SapientChat") — a collision makes Xcode bind the app scheme to the
// package and destination resolution fails with "supported platforms empty".
let package = Package(
    name: "SapientChatKit",
    platforms: [.macOS(.v13), .iOS(.v16)],
    products: [
        .library(name: "SapientChatUI", targets: ["SapientChatUI"])
    ],
    dependencies: [
        // Generated by scripts/package-swift.sh — XCFramework + bindings.
        .package(path: "../../dist/mobile/sapient-swift")
    ],
    targets: [
        .target(
            name: "SapientChatUI",
            dependencies: [.product(name: "Sapient", package: "sapient-swift")],
            path: "Sources/SapientChatUI"
        ),
        .executableTarget(
            name: "SapientChatMac",
            dependencies: ["SapientChatUI"],
            path: "Sources/SapientChatMac"
        ),
    ]
)
