# Homebrew formula for SAPIENT
# Location: https://github.com/SkidGod4444/homebrew-tap/blob/main/Formula/sapient.rb
#
# To publish:
#   1. Create a repo at github.com/SkidGod4444/homebrew-tap
#   2. Put this file at Formula/sapient.rb
#   3. Users install with: brew install skidgod4444/tap/sapient
#
# To update after a new release, run the update script:
#   ./scripts/update-homebrew-formula.sh v0.2.0

class Sapient < Formula
  desc "LLM & SLM inference engine — run any HuggingFace model locally"
  homepage "https://github.com/SkidGod4444/sapient"
  license "GPL-3.0-only"
  version "0.1.1"

  # ── Bottles (pre-built binaries) — generated by CI ─────────────────────────
  # These are filled in automatically by the release workflow.
  # To generate locally: brew bottle sapient

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SkidGod4444/sapient/releases/download/v#{version}/sapient-aarch64-apple-darwin.tar.gz"
      sha256 "REPLACE_WITH_SHA256_AARCH64_APPLE_DARWIN"
    else
      url "https://github.com/SkidGod4444/sapient/releases/download/v#{version}/sapient-x86_64-apple-darwin.tar.gz"
      sha256 "REPLACE_WITH_SHA256_X86_64_APPLE_DARWIN"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/SkidGod4444/sapient/releases/download/v#{version}/sapient-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "REPLACE_WITH_SHA256_AARCH64_LINUX"
    else
      url "https://github.com/SkidGod4444/sapient/releases/download/v#{version}/sapient-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "REPLACE_WITH_SHA256_X86_64_LINUX"
    end
  end

  def install
    bin.install "sapient"
  end

  # Shell completions (generated at install time)
  def post_install
    system "#{bin}/sapient", "completions", "bash",  "--output", "#{HOMEBREW_PREFIX}/etc/bash_completion.d/sapient" rescue nil
    system "#{bin}/sapient", "completions", "zsh",   "--output", "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_sapient" rescue nil
    system "#{bin}/sapient", "completions", "fish",  "--output", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/sapient.fish" rescue nil
  end

  test do
    assert_match "sapient", shell_output("#{bin}/sapient --version")
  end
end
